### ISSUE TITLE
Stale Episode list

### ISSUE THREAD

**Issue by xmcnuggetx** [plexinc-plugins/NBC.bundle#19]
Episode lists appear stale (wondering if NBC is using something different now for their app or iPad app is broken too).  I don't have an iPad to see if it is out of sync as well.  I have an android phone and the episodes listed are up to date.  You can check examples from tonight show or days of our lives.  I'll put tonight show links below for ease.

website (newest listed 156):
http://www.nbc.com/the-tonight-show/episodes

ipad feed (newest listed 149):
http://tveatc-usa.nbcuni.com/awe3/live/5/nbce/containers/iPad/the-tonight-show?seasonNumber=4&filterBy=episode

**Comment by shopgirl284** [comment]
Something has changed in their Ipad code, so the channel will need to at least be updated if not completely rewritten.

**Comment by sander1** [comment]
A completely rewritten channel will be released today. It should fix all outstanding issues.
