### ISSUE TITLE
New episodes not showing up

### ISSUE THREAD

**Issue by xmcnuggetx** [plexinc-plugins/NBC.bundle#9]
Examples are:

http://www.nbc.com/dateline
S02E15 - 1/2/15 - The Man Who Wasn't There

http://www.nbc.com/days-of-our-lives/video
S50E71 - 12/31/14 - Wednesday, December 31, 2014
S50E72 - 1/02/15 - Friday, January 2, 2015

**Comment by sander1** [comment]
We're not using the website as a source, we're using the feed that's being used by their app. If this feed is not updated, the content of the channel is not updated too, but there's very little we can do about that :(

**Comment by xmcnuggetx** [comment]
I have the nbc app on my android phone and see the episodes listed.  Is it a different feed your monitoring?
